export const groupInfo: { [key: string]: string } = {
  "Main Menu": "Welcome to the main menu!",
  "Vip Signal": "VIP Signal section",
  "Mentorship": "Mentorship section",
  "Partnership": "Partnership section",
  "Fund Management": "Fund Management section",
  "Broker": "Broker section",
  "Prop Firm": "Prop Firm section",
  "3 Days BootCamp": "3 Days BootCamp section",
  "Settings": "Settings section",
  "FAQ": "Frequently Asked Questions",
  "Payment": "Payment section",
  "USDT": "USDT Payment",
  "Naira Payment": "Naira Payment",
  "BTC": "BTC Payment",
  "Ethereum Payment": "Ethereum Payment",
  "Skrill Payment": "Skrill Payment",
  "Foreign Payment": "Foreign Payment",
  "Check Subscription Status": "Check Subscription Status",
  "Gift Coupon": "Gift Coupon",
  "Generate Coupon": "Generate Coupon",
  "Vip Discount Price": "Vip Discount Price",
  "Vip Prices": "Vip Prices",
  "Generate Code": "Generate Code"
}; 